# Generated by Django 4.0.6 on 2022-09-02 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_goal_for_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tomeet',
            old_name='persone',
            new_name='person',
        ),
    ]
