# Generated by Django 4.0.6 on 2022-09-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_rename_persone_tomeet_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('done_for_today', models.BooleanField(default=False)),
                ('important', models.BooleanField(default=False)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='goal_for_month',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal_for_month',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='goal_for_month',
            name='difficulty',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='goal_for_month',
            name='month',
            field=models.CharField(max_length=30),
        ),
    ]
